// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNsh1OebR3wH-7azBeXaTjuz9XiMAhr7k',
    appId: '1:936254452244:web:7c3888951076c86192ad01',
    messagingSenderId: '936254452244',
    projectId: 'moviesnack-65c0f',
    authDomain: 'moviesnack-65c0f.firebaseapp.com',
    storageBucket: 'moviesnack-65c0f.appspot.com',
    measurementId: 'G-V0E3BZJ7QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzK9gpiVOixb8AmB9A6JS33gT3R4l6TXQ',
    appId: '1:936254452244:android:e55ac66dfd9b5c1292ad01',
    messagingSenderId: '936254452244',
    projectId: 'moviesnack-65c0f',
    storageBucket: 'moviesnack-65c0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQdIemLTWLdYxdFe4cS278IgAZVtIVkzY',
    appId: '1:936254452244:ios:744c5020275e8dee92ad01',
    messagingSenderId: '936254452244',
    projectId: 'moviesnack-65c0f',
    storageBucket: 'moviesnack-65c0f.appspot.com',
    iosBundleId: 'com.example.movieSnack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQdIemLTWLdYxdFe4cS278IgAZVtIVkzY',
    appId: '1:936254452244:ios:744c5020275e8dee92ad01',
    messagingSenderId: '936254452244',
    projectId: 'moviesnack-65c0f',
    storageBucket: 'moviesnack-65c0f.appspot.com',
    iosBundleId: 'com.example.movieSnack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNsh1OebR3wH-7azBeXaTjuz9XiMAhr7k',
    appId: '1:936254452244:web:1492b01969b5a55c92ad01',
    messagingSenderId: '936254452244',
    projectId: 'moviesnack-65c0f',
    authDomain: 'moviesnack-65c0f.firebaseapp.com',
    storageBucket: 'moviesnack-65c0f.appspot.com',
    measurementId: 'G-MRWMF5QL8D',
  );
}
